service: retina-sf-dev
runtime: nodejs20
env: standard
env_variables:
  PROJECT: telkomsel-retail-intelligence
  APPLICATION_TITLE: Retina SF Uploader
  APPLICATION_PORT: 8080 
  DBHOST:  
  DBNAME: 
  DBUSER: 
  DBPASSWORD: 
  DBENGINE: postgresql 
  AUTH_DBHOST: 
  AUTH_DBNAME:  
  AUTH_DBUSER:  
  AUTH_DBPASSWORD: 
  AUTH_DBENGINE: postgresql 
  PUBSUB_UPLOAD_XLS_DONE: projects/telkomsel-retail-intelligence/topics/uploaded-xls-done-dev
  PUBSUB_CONVERT_XLS_CSV_DONE: projects/telkomsel-retail-intelligence/topics/convert-xls-csv-done-dev
  PUBSUB_SAVE_STORE_USER_TEMP_DONE: projects/telkomsel-retail-intelligence/topics/save-store-user-temp-done-dev
  PUBSUB_PROCESS_STORE_USER_TEMP_DONE: projects/telkomsel-retail-intelligence/topics/process-store-user-temp-done-dev
  PUBSUB_TRANSFER_FROM_TEMPORARY_DONE: projects/telkomsel-retail-intelligence/topics/transfer-from-temporary-done-dev

